-- =====================================================================
-- Migration: KHQR-based manual billing for QRserve
-- Replaces LemonSqueezy as the primary billing flow.
-- Keeps restaurants.billing_type = 'manual' (already allowed by your
-- existing CHECK constraint) — this just gives "manual" a real,
-- auditable payment trail via Bakong KHQR instead of a bare form.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. platform_settings — YOUR (QRserve's) own Bakong account.
--    Single row, enforced by the boolean PK trick (id must be `true`).
-- ---------------------------------------------------------------------
CREATE TABLE public.platform_settings (
  id boolean NOT NULL DEFAULT true PRIMARY KEY CHECK (id),
  bakong_account_id text,              -- e.g. 'seth@aclb' or your phone-based ID
  merchant_name text NOT NULL DEFAULT 'QRserve',
  merchant_city text NOT NULL DEFAULT 'Phnom Penh',
  currency text NOT NULL DEFAULT 'USD' CHECK (currency IN ('USD', 'KHR')),
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES public.users(id)
);

INSERT INTO public.platform_settings (id, merchant_name) VALUES (true, 'QRserve');

-- ---------------------------------------------------------------------
-- 2. plans — pricing config, editable without a redeploy.
--    monthly_fee is the flat base price. transaction_fee_percent is
--    charged on the restaurant's order volume for the billing period.
-- ---------------------------------------------------------------------
CREATE TABLE public.plans (
  id text PRIMARY KEY,                  -- 'starter' | 'pro'
  display_name text NOT NULL,
  monthly_fee numeric NOT NULL CHECK (monthly_fee >= 0),
  transaction_fee_percent numeric NOT NULL CHECK (transaction_fee_percent >= 0),
  max_tables integer,                   -- NULL = unlimited
  max_staff integer,                    -- NULL = unlimited
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.plans (id, display_name, monthly_fee, transaction_fee_percent, max_tables, max_staff) VALUES
  ('starter', 'Starter', 10, 2.00, 15, 3),
  ('pro',     'Pro',     20, 1.00, NULL, 10);

-- ---------------------------------------------------------------------
-- 3. subscription_invoices — one row per billing cycle per restaurant.
--    Generated by the edge function (server computes the amount —
--    never trust a client-submitted total for a payment QR).
-- ---------------------------------------------------------------------
CREATE TABLE public.subscription_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  restaurant_id uuid NOT NULL REFERENCES public.restaurants(id),
  plan_id text NOT NULL REFERENCES public.plans(id),
  period_start date NOT NULL,
  period_end date NOT NULL,
  order_volume numeric NOT NULL DEFAULT 0,        -- restaurant's total order value in period
  base_fee numeric NOT NULL,
  transaction_fee_amount numeric NOT NULL,
  total_amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'USD',
  khqr_string text,
  khqr_md5 text,                                  -- used to poll Bakong for payment confirmation
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'void')),
  paid_at timestamptz,
  confirmed_by uuid REFERENCES public.users(id),  -- super admin who marked it paid
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_subscription_invoices_restaurant ON public.subscription_invoices(restaurant_id);
CREATE INDEX idx_subscription_invoices_status ON public.subscription_invoices(status);

-- ---------------------------------------------------------------------
-- 4. RLS — only super admins touch these tables directly.
--    Restaurant admins can only SELECT their own restaurant's invoices.
-- ---------------------------------------------------------------------
ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscription_invoices ENABLE ROW LEVEL SECURITY;

-- platform_settings: super admin only, full access
CREATE POLICY platform_settings_super_admin ON public.platform_settings
  FOR ALL
  USING (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_super_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_super_admin));

-- plans: everyone authenticated can read (so restaurant admins see pricing/limits),
-- only super admin can write
CREATE POLICY plans_read_all ON public.plans
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY plans_write_super_admin ON public.plans
  FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_super_admin));

CREATE POLICY plans_update_super_admin ON public.plans
  FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_super_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_super_admin));

-- subscription_invoices: super admin full access
CREATE POLICY invoices_super_admin_all ON public.subscription_invoices
  FOR ALL
  USING (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_super_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.is_super_admin));

-- subscription_invoices: restaurant admin can view their own restaurant's invoices
CREATE POLICY invoices_restaurant_read_own ON public.subscription_invoices
  FOR SELECT
  USING (
    restaurant_id IN (SELECT restaurant_id FROM public.users WHERE id = auth.uid())
  );

-- ---------------------------------------------------------------------
-- 5. Optional: keep the LemonSqueezy edge functions in place but dormant.
--    No need to drop lemonsqueezy_customer_id / lemonsqueezy_subscription_id
--    columns on restaurants — they're just unused now. billing_type stays
--    'manual' for every restaurant going forward.
-- ---------------------------------------------------------------------
